name: Build check
on: 
  pull_request:
    paths-ignore:
      - "*.md"
    types:
      - opened
      - synchronize
      - reopened
  push:
    paths-ignore:
      - "*.md"
    branches:
      - main
      - feedback_loop_layout

jobs:
  build:
    uses: ./.github/workflows/build.yml
